import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    minHeight: "100%",
    backgroundColor: "#f8f9fa",
    gap: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    padding: 20,
    paddingTop: 40,
    backgroundColor: "#19536e",
  },
  headerTitle: {
    fontSize: 20,
    color: "#fff",
    fontWeight: "bold",
  },
  botaoSair: {
    backgroundColor: "#fff",
    padding: 8,
    borderRadius: 8,
    fontWeight: "bold",
    color: "#19536e",
  },
  botaoAdicionar: {
    backgroundColor: "#19536e",
    padding: 8,
    borderRadius: 8,
    fontWeight: "bold",
    color: "#fff",
    fontSize: 18,
  },
  list: {
    width: "100%",
    alignItems: "center",
  },
  card: {
    backgroundColor: "#fff",
    borderColor: "#19536e",
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    width: "90%",
    gap: 10,
    marginBottom: 20,
  },
  imagem: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    resizeMode: "cover",
  },
  data: {
    borderRadius: 12,
    backgroundColor: "#19536e",
    width: 100,
    textAlign: "center",
    padding: 8,
    color: "#fff",
    fontWeight: "bold",
  },

  titulo: {
    fontSize: 24,
    fontWeight: "600",
    marginVertical: 8,
  },
  endereco: {
    fontWeight: "600",
    fontSize: 16,
  },
  botoes: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 20,
  },
  botaoEditar: {
    backgroundColor: "#19536e",
    borderRadius: 12,
    paddingVertical: 12,
    width: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  botaoExcluir: {
    backgroundColor: "#6e191d",
    borderRadius: 12,
    paddingVertical: 12,
    width: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  botaoText: {
    color: "#fff",
    fontWeight: "bold",
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 1000,
    alignItems: "center",
    justifyContent: "center",
  },
  modal: {
    flexDirection: "column",
    backgroundColor: "#0c2e3d",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 20,
    maxWidth: 500,
    width: "90%",
    elevation: 5,
    gap: 10,
  },
  modalTitle: {
    fontSize: 24,
    color: "#fff",
    marginBottom: 20,
    fontWeight: "500",
  },
  botaoImagem: {
    backgroundColor: "#19536e",
    borderRadius: 12,
    paddingVertical: 12,
    width: 200,
    justifyContent: "center",
    alignItems: "center",
  },
  botaoSalvar: {
    backgroundColor: "#19536e",
    borderRadius: 12,
    paddingVertical: 12,
    width: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  botaoCancelar: {
    backgroundColor: "#6e191d",
    borderRadius: 12,
    paddingVertical: 12,
    width: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  input: {
    backgroundColor: "#797d80",
    color: "#000",
    fontSize: 14,
    padding: 16,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "#bbb",
  },
});
